Ext.define('Ext.cutover.model.Cutover', {
    extend: 'Ext.data.Model',
    requires: [
       'Ext.date.*'
    ], 
    fields: [
		'jobId',
		'firstDetailId',
		'startExpectDate',
		'startExpectTime',
		'endExpectDate',
		'endExpectTime',
		{ name: 'duration', type: 'int'},
		'systemType',
		'jobStep',
		'jobType',
		'xCategory',
		'yCategory',
		'jobSortId',
		'task',
		'activity',
		'jobExecutionTeam',
		'jobExecutor',
		'backup',
		'jobCheckList',
		'caution',
		'supervisor',
		'ktSupervisor',
		'etc',
		'jiraId',
		'jiraStatus',
		'jiraDueDate',
		'resolution',
		'cutoverTh',
		'assignee',
		'issueLink',
		'preJob',
		'jiraStatusDesc',
		'itemStatusName',
		'mode',
		'jobExecutionTeamName',
		'sortNo',
		'jobExecutorId',
		'supervisorId',
		'jiraSyncMessage',
		'itemStatus',
		'itemAuthor'
    ]
});